<?php
/**
 * Copy of the live dynamiqes.com About Us page and Privacy Policy (fetched 2026-09-07).
 * The old site is the SEO benchmark: page-about-us.php and page-privacy-policy.php render this copy
 * with the live heading structure; content typed into the pages in WP Admin takes precedence.
 * Generated by scrape_pages.py.
 *
 * @package dynamiqes
 */

defined( 'ABSPATH' ) || exit;

/** About Us copy, verbatim from dynamiqes.com/about-us/. */
function dq_about_copy() {
	return apply_filters( 'dq_about_copy', array(
		'h1'             => 'About DynamIQ',
		'intro'          => array(
			'<strong>DYNAMIQ ENTERPRISE SOLUTIONS INC</strong> is a Philippine-based professional IT consultancy service that provides the right balance between applications and consulting to help businesses resolve challenges in managing their operations. We are more than just a software vendor. We devise a total ENTERPRISE RESOURCE PLANNING (ERP) SYSTEM experience that is truly customer-focused and remarkably life centered to sustain a balance between your personal and professional priorities.',
		),
		'mission'        => 'To be the preferred provider of business technology solutions and services for the small, medium, and large enterprises in the Philippines.',
		'vision'         => 'To redefine the method of doing business in the country, through our excellent business technology solutions and services.',
		'values_h2'      => 'Our Core Values',
		'values'         => array(
			array( 'DRIVEN', 'Our company offers a wide range of technology based solutions, with the aim of helping businesses achieve their goals, improve their efficiency, and stay ahead of the competition.' ),
			array( 'DEPENDABLE', 'We are committed to provide our clients with the most relevant and responsive IT support services, delivered with a customer-oriented, professional, in-depth, and, knowledgeable attitude.' ),
			array( 'DEDICATED', 'The company is passionate in helping businesses improved their operational efficiency and productivity by continuously educating, training and, developing our experienced team members, to ensure that we adapt to the dynamic business landscape.' ),
			array( 'DATA SECURITY', 'We are committed to ensuring the confidentiality, integrity, and availability of our customers\' information by adhering to strict data security protocols.' ),
		),
		'products_h2'    => 'Our Products',
		'products_intro' => 'We are more than just a software vendor. We devise a total ENTERPRISE RESOURCE PLANNING (ERP) SYSTEM experience that is truly customer-focused and remarkably life centered to sustain a balance between your personal and professional priorities. Here are some of our products:',
		'products'       => array(
			array( 'name' => 'SAP Business One', 'paras' => array(
				'SAP Business One is an application that lets you manage your entire business operations easily and effectively. It comes with built-in modules that represent the business areas of your operation.',
				'The main capabilities of the system range from financial management, sales and customer management, purchasing and inventory control, up to production planning, and project management. It also covers analytics and reporting so you can make timely decisions based on real-time data.',
				'SAP Business One is a full-scale and highly functional ERP system designed specifically for small businesses up to small and mid-size enterprises.',
			) ),
			array( 'name' => 'IQ Portal', 'paras' => array(
				'Unlock the full potential of your SAP Business One system with our powerful add-on, designed to seamlessly enhance your ERP experience through the web. Our secure, user-friendly portal allows you to access and manage critical business data anytime, anywhere.',
				'Tailored to provide a lighter and faster experience, this solution empowers you to extend selected data and functionalities of SAP Business for better and more personalized user experience and integration to other 3rd party solutions. This ensures that you can streamline processes and respond to business needs effectively, all while enjoying the flexibility to work on your terms.',
			) ),
			array( 'name' => 'IQ Tax', 'paras' => array(
				'While BIR’s intent to digitized is clear, many taxpayers oftentimes find themselves in disarray with the process because of its complicated forms and risky manual data entry. This is why businesses need a reliable accounting system in the Philippines.We have created an application suitably compatible with SAP Business One to reduce the tax filing bottlenecks and enhance paperless tax filing experience.',
				'DYNAMIQ BIR TAX MODULE, our proprietary taxation program, is designed to make tax filing and compliance easy and accessible at a click of a button. It is in compliance to the computerized accounting system (CAS) and in pursuance to BIR-issued Revenue Regulation (RR) 9-2009 and Revenue Memorandum 29-2002.',
			) ),
			array( 'name' => 'IQ Barcode', 'paras' => array(
				'DYNAMIQ BARCODING is a barcode inventory system and a third- party integration for SAP Business One (SAP B1). It utilizes the logistics using barcoding and scanning items.',
			) ),
			array( 'name' => 'IQ Link', 'paras' => array(
				'IQ Link brings together various types of software sub-systems so that they create a unified single system. Software integration maybe required on the following situations i.e., integrating SAP B1 to the current POS system used or any other related software. IQ Link has a status report which lets you know if there are any data inconsistencies as well.',
			) ),
			array( 'name' => 'IQ REM', 'paras' => array(
				'IQ REM is a real estate management add-on built to extend SAP Business One for developers and real estate businesses. It centralizes property sales, contracts, billing, and financial transactions into one integrated platform, simplifying day-to-day operations.',
				'Fully embedded within SAP Business One, IQ REM operates from a single source of truth, eliminating manual work and disconnected systems. It supports residential, commercial, and mixed-use properties, with flexible configurations for unit types, pricing, and contracts to match each project’s requirements.',
			) ),
			array( 'name' => 'IQ Ai', 'paras' => array(
				'IQ Ai is DynamIQ’s intelligent engine that enhances SAP Business One with Ai-powered insights. Using machine learning and intelligent automation, it turns complex business data into actionable recommendations, helping teams make smarter decisions faster.',
				'From sales forecasting to inventory management, IQ Ai streamlines workflows and reduces manual tasks. With real-time analytics and predictive insights, it empowers businesses to act proactively and stay ahead of trends.',
			) ),
			array( 'name' => 'IQ Desk', 'paras' => array(
				'IQDesk is a comprehensive IT Service Management (ITSM) and helpdesk solution engineered to optimize support workflows through AI-driven ticketing and real-time escalation. By integrating robust asset lifecycle management and PAR tracking, the platform ensures organizational accountability and operational excellence, delivering a seamless, automated approach to modern IT service delivery.',
			) ),
			array( 'name' => 'IQ Ecom', 'paras' => array(
				'IQEcom is an enterprise-level e-commerce platform offering seamless SAP Business One integration for both B2B and B2C environments. It streamlines complex commerce through customer-specific pricing, real-time inventory synchronization across multiple warehouses, and automated sales workflows. The platform eliminates manual overhead, ensuring data accuracy and scalability for high-growth digital enterprises.',
			) ),
		),
		'services_h2'    => 'Services We Offer',
		'services_p'     => 'SAP Business One is only as good as the company that implements it. The true value of SAP Business One lies dependently in the design that has been meticulously put together to serve your business demands not just today but a few years from now.',
		'customers_h2'   => 'Hear From Our Customers',
	) );
}

/** Privacy Policy body, verbatim from dynamiqes.com/privacy-policy/ (H5 section headings, as published). */
function dq_privacy_policy_html() {
	return <<<'HTML'
<p>Last updated January 01, 2022</p>
<p>This privacy notice for Dynamiq Enterprise Solutions (“Company,” “we,” “us,” or “our“), describes how and why we might collect, store, use, and/or share (“process“) your information when you use our services (“Services“), such as when you:</p>
<ul>
</ul>
<p>Visit our website at <a href="https://www.dynamiqes.com/">https://www.dynamiqes.com/</a>, or any website of ours that links to this privacy notice Engage with us in other related ways, including any sales, marketing, or events</p>
<p><strong>Questions or concerns?</strong> Reading this privacy notice will help you understand your privacy rights and choices. If you do not agree with our policies and practices, please do not use our Services. If you still have any questions or concerns, please contact us at sales@dynamiqes.com.</p>
<h5>SUMMARY OF KEY POINTS</h5>
<p><em><strong>This summary provides key points from our privacy notice, but you can find out more details about any of these topics by clicking the link following each key point or by using our table of contents below to find the section you are looking for. You can also click here to go directly to our table of contents.</strong></em></p>
<p><strong>What personal information do we process?</strong> When you visit, use, or navigate our Services, we may process personal information depending on how you interact with Dynamiq Enterprise Solutions and the Services, the choices you make, and the products and features you use. Click here to learn more.</p>
<p><strong>Do we process any sensitive personal information?</strong> We do not process sensitive personal information.</p>
<p><strong>Do we receive any information from third parties?</strong> We do not receive any information from third parties.</p>
<p><strong>How do we process your information?</strong> We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent. We process your information only when we have a valid legal reason to do so. Click here to learn more.</p>
<p><strong>In what situations and with which parties do we share personal information?</strong> We may share information in specific situations and with specific third parties. Click here to learn more.</p>
<p><strong>How do we keep your information safe?</strong> We have organizational and technical processes and procedures in place to protect your personal information. However, no electronic transmission over the internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information. Click here to learn more</p>
<p><strong>What are your rights?</strong> Depending on where you are located geographically, the applicable privacy law may mean you have certain rights regarding your personal information. Click here to learn more.</p>
<p><strong>How do I exercise my rights?</strong> The easiest way to exercise your rights is by filling out our data subject request form available here, or by contacting us. We will consider and act upon any request in accordance with applicable data protection laws.</p>
<p>Want to learn more about what Dynamiq Enterprise Solutions does with any information we collect? Click here to review the notice in full.</p>
<h5>TABLE OF CONTENTS</h5>
<ol>
<li>WHAT INFORMATION DO WE COLLECT?</li>
<li>HOW DO WE PROCESS YOUR INFORMATION?</li>
<li>WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</li>
<li>HOW LONG DO WE KEEP YOUR INFORMATION?</li>
<li>HOW DO WE KEEP YOUR INFORMATION SAFE?</li>
<li>DO WE COLLECT INFORMATION FROM MINORS?</li>
<li>WHAT ARE YOUR PRIVACY RIGHTS?</li>
<li>CONTROLS FOR DO-NOT-TRACK FEATURES</li>
<li>DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</li>
<li>DO WE MAKE UPDATES TO THIS NOTICE?</li>
<li>HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</li>
<li>HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</li>
</ol>
<h5>1. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</h5>
<p><strong>Personal information you disclose to us</strong></p>
<p><strong>In Short:</strong>We collect personal information that you provide to us.</p>
<p>We collect personal information that you voluntarily provide to us when you express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us.</p>
<p><strong>Personal Information Provided by You.</strong> The personal information that we collect depends on the context of your interactions with us and the Services, the choices you make, and the products and features you use. The personal information we collect may include the following:</p>
<ul>
<li>names</li>
<li>phone numbers</li>
<li>email addresses</li>
<li>mailing addresses</li>
<li>contact preferences</li>
<li>contact or authentication data</li>
</ul>
<p><strong>Sensitive Information.</strong> We do not process sensitive information.</p>
<p>All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.</p>
<h5>2. HOW DO WE PROCESS YOUR INFORMATION?</h5>
<p><em><strong>In Short:</strong> We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent.</em></p>
<p><strong>We process your personal information for a variety of reasons, depending on how you interact with our Services, including:</strong></p>
<ul>
<li>To deliver and facilitate delivery of services to the user. We may process your information to provide you with the requested service.</li>
</ul>
<h5>3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</h5>
<p><em><strong>In Short:</strong> We may share information in specific situations described in this section and/or with the following third parties.</em></p>
<p>We may need to share your personal information in the following situations:</p>
<ul>
<li><strong>Business Transfers.</strong> We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.</li>
<li><strong>Business Partners.</strong> We may share your information with our business partners to offer you certain products, services, or promotions.</li>
</ul>
<h5>4. HOW LONG DO WE KEEP YOUR INFORMATION?</h5>
<p><em><strong>In Short:</strong> We keep your information for as long as necessary to fulfill the purposes outlined in this privacy notice unless otherwise required by law.</em></p>
<p>We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements). No purpose in this notice will require us keeping your personal information for longer than 2 years.</p>
<p>When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize such information, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.</p>
<h5>5. HOW DO WE KEEP YOUR INFORMATION SAFE?</h5>
<p><em><strong>In Short:</strong> We aim to protect your personal information through a system of organizational and technical security measures.</em></p>
<p>We have implemented appropriate and reasonable technical and organizational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information. Although we will do our best to protect your personal information, transmission of personal information to and from our Services is at your own risk. You should only access the Services within a secure environment.</p>
<h5>6. DO WE COLLECT INFORMATION FROM MINORS?</h5>
<p><em><strong>In Short:</strong> We do not knowingly collect data from or market to children under 18 years of age.</em></p>
<p>We do not knowingly solicit data from or market to children under 18 years of age. By using the Services, you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent’s use of the Services. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we may have collected from children under age 18, please contact us at __________.</p>
<h5>7. WHAT ARE YOUR PRIVACY RIGHTS?</h5>
<p><em><strong>In Short:</strong> You may review, change, or terminate your account at any time.</em></p>
<p>If you are located in the EEA or UK and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here: <a href="https://edpb.europa.eu/about-edpb/about-edpb/members_en">https://edpb.europa.eu/about-edpb/about-edpb/members_en</a>.</p>
<p>If you are located in Switzerland, the contact details for the data protection authorities are available here: <a href="https://edpb.europa.eu/about-edpb/about-edpb/members_en">https://edpb.europa.eu/about-edpb/about-edpb/members_en</a>.</p>
<p>Withdrawing your consent: If we are relying on your consent to process your personal information, which may be express and/or implied consent depending on the applicable law, you have the right to withdraw your consent at any time. You can withdraw your consent at any time by contacting us by using the contact details provided in the section “HOW CAN YOU CONTACT US ABOUT THIS NOTICE?” below.</p>
<p>However, please note that this will not affect the lawfulness of the processing before its withdrawal, nor when applicable law allows, will it affect the processing of your personal information conducted in reliance on lawful processing grounds other than consent.</p>
<h5>8. CONTROLS FOR DO-NOT-TRACK FEATURES</h5>
<p>Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track (“DNT”) feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. At this stage no uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this privacy notice.</p>
<h5>9. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</h5>
<p><em><strong>In Short:</strong> Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information.</em></p>
<p>California Civil Code Section 1798.83, also known as the “Shine The Light” law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.</p>
<p>If you are under 18 years of age, reside in California, and have a registered account with Services, you have the right to request removal of unwanted data that you publicly post on the Services. To request removal of such data, please contact us using the contact information provided below and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Services, but please be aware that the data may not be completely or comprehensively removed from all our systems (e.g., backups, etc.).</p>
<h5>10. DO WE MAKE UPDATES TO THIS NOTICE?</h5>
<p><em><strong>In Short:</strong> Yes, we will update this notice as necessary to stay compliant with relevant laws.</em></p>
<p>We may update this privacy notice from time to time. The updated version will be indicated by an updated “Revised” date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy notice frequently to be informed of how we are protecting your information.</p>
<h5>11. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</h5>
<p>If you have questions or comments about this notice, you may email us at <a href="mailto:sales@dynamiqes.com">sales@dynamiqes.com</a> or by post to:</p>
<p>Dynamiq Enterprise Solutions</p>
<p>No. 12 Tagdalit Street, Manresa, Quezon City 1115</p>
<p>Metro Manila, Metro Manila</p>
<p>Philippines</p>
<h5>12. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</h5>
<p>Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please submit a request form by clicking here.</p>
<p>This privacy policy was created using Termly’s Privacy Policy Generator.</p>
HTML;
}
