<?php
/**
 * Live product-page content — the copy, headings and section order of dynamiqes.com/products/<slug>/
 * as published (fetched 2026-09-07). The old site is the SEO benchmark, so this
 * overrides the catalogue defaults in inc/product-data.php: H1, hero paragraph, title tag /
 * meta description and the ordered `sections` each product page renders (single-dq_product.php).
 *
 * Generated by scrape_products.py from the live HTML; edit in WP Admin (Products → Product details)
 * rather than here — saved meta overrides these defaults field by field.
 *
 * @package dynamiqes
 */

defined( 'ABSPATH' ) || exit;

/** @return array<string, array> key => overrides for dq_product_defaults(). */
function dq_product_live_content() {
	return array(
		'sap' => array(
			'title'           => 'Drive Success with SAP Business One Solutions in the Philippines',
			'description'     => 'Future-proof your business in the Philippines with SAP Business One. DynamIQ is offering you the best enterprise resource planning system that will help manage all your business in one application!',
			'seo_title'       => 'SAP Business One Philippines | DynamIQ',
			'seo_description' => 'Transform your business with SAP Business One in the Philippines. Partner with DynamIQ, a leading provider of SAP software solutions.',
			'overview_title'  => 'Product Overview',
			'overview'        => array(
				'SAP Business One is a full-scale and highly functional ERP system designed specifically for small businesses up to small and mid-size enterprises. It is an enterprise management system that works on a centralized database that connects all of your business units and employees through a single application.',
				'With SAP B1’s completely integrated functionality, you can have a 360-degree view of all your business functions, a much-streamlined flow of key processes, greater control and sharper insight over and into your business, and more precise decision-making based on real-time information. As a result, the corporate performance of the entire organization is utilized to the fullest towards driving profitable growth.',
				'DynamIQ is the leading provider of SAP Software in the Philippines. Improve your business processes by inquiring today!',
			),
			'closing'         => '',
			'faqs'            => array(
				array( 'Are there industry-specific modules or add-ons available for SAP Business One?', '<p>Yes. This software offers a wide range of industry-specific and horizontal solutions developed by SAP partners globally, including those based in the Philippines. These add-ons address specialized requirements in sectors like manufacturing, pharmaceuticals, food and beverage, retail, automotive, and professional services. Local partners can also provide custom extensions tailored to unique operational needs.</p>' ),
				array( 'What are the minimum hardware or system requirements to run this software?', '<p>In general, SAP B1 runs on a Windows-based environment and requires the following minimum specifications:</p><ul><li>Processor: Intel® Xeon® E3 or equivalent</li><li>Memory (RAM): At least 4 GB (16–32 GB recommended for optimal performance)</li><li>Hard Disk: Minimum of 32 GB for the system partition and 10–15 GB for the data partition</li><li>Operating System: 64-bit versions of supported Windows Server editions</li><li>Network: Stable, high-speed internet connection with low latency</li></ul>' ),
				array( 'Is SAP Business One available as a cloud-based, on-premise, or hybrid solution?', '<p>Yes. SAP Business One in the Philippines is available in cloud-based, on-premise, and hybrid deployment models. This flexibility allows businesses to align the system with their existing IT infrastructure, budget, and strategic goals. As a trusted partner, we at DynamIQ can provide both cloud and on-premise implementations.</p>' ),
				array( 'How long does a typical implementation take?', '<p>Implementation timelines vary depending on business complexity and customization. However, with DynamIQ’s meticulous methodology and deep experience with local clients, most SAP for SMEs implementations in the Philippines are completed within 3 to 6 months. This ensures a cost-efficient rollout with minimal operational disruption.</p>' ),
				array( 'What post-implementation support is included with SAP Business One?', '<p>At DynamIQ, we offer post-implementation support tailored to Philippine SMEs, including localized user training, proactive system health checks, fast-tracked troubleshooting, and direct access to SAP-certified consultants. This ensures that your system continues to deliver value long after go-live. Support is delivered through multiple channels to ensure your SAP B1 system runs smoothly and continues to evolve with your business.</p>' ),
			),
			'faq_heading'     => 'h3',
			'sections'        => array(
				array(
					'type'    => 'generic',
					'title'   => 'Why Choose DynamIQ as your SAP Premier Partner?',
					'intro'   => array(
						'When selecting a partner to support your small or medium-sized enterprise with SAP Business One, look no further than DynamIQ. As a SAP Premier Partner, we bring wealth of expertise and specialized knowledge to the table, ensuring that our approach is not only tailored specifically to your needs but also innovative and forward-thinking.',
					),
					'items'   => array(
						array( 'title' => 'Certified SAP Premier Partner', 'text' => '', 'items' => array() ),
						array( 'title' => 'Top 5 SAP & Automation Providers in the Philippines', 'text' => '', 'items' => array() ),
						array( 'title' => '5.0-Star Customer Rating', 'text' => '', 'items' => array() ),
						array( 'title' => 'High Success Rate', 'text' => '', 'items' => array() ),
					),
				),
				array(
					'type'    => 'cta',
					'title'   => 'Contact Us Today!',
					'kicker'  => 'Ready To Get Started?',
					'kicker_text' => 'If you contact us today, we will reply to you within 24 hours!',
					'intro'   => array(
						'If you contact us today, our team will reply to you within 24 hours. You’re just a few steps away from consulting our SAP B1 specialist about how we at DynamIQ can help you.',
					),
				),
				array(
					'type'    => 'overview',
				),
				array(
					'type'    => 'generic',
					'title'   => 'Key Benefits of Using SAP Business One in the Philippines',
					'intro'   => array(
						'Recognized as a trusted ERP solution in the Philippines, SAP Business One is built specifically for small and medium-sized enterprises (SMEs), helping streamline core operations, enhance visibility, and support long-term growth. Its all-in-one functionality and flexible deployment help local businesses digitize and scale efficiently, making this SAP software an ideal solution for SMEs.',
					),
					'items'   => array(
						array( 'title' => 'Complete and Integrated', 'text' => 'This solution seamlessly links your finance, sales, purchasing, inventory, and customer service functions into a unified platform. By breaking down departmental barriers, the software improves data accuracy and fosters smoother teamwork throughout your organization.', 'items' => array() ),
						array( 'title' => 'Scalable and Innovative', 'text' => 'Built to evolve with your growing business, this software easily handles more transactions, users, and operational complexity. The newest version introduces cloud-first architecture and a web-based client, giving you access to the latest technologies without disruption.', 'items' => array() ),
						array( 'title' => 'Easy-to-Use', 'text' => 'The software features a clean, user-focused interface inspired by SAP Fiori design standards. Employees can navigate tools quickly on both desktop and browsers, minimizing training needs and speeding up adoption.', 'items' => array() ),
						array( 'title' => 'Simple and Affordable', 'text' => 'Offering enterprise-grade capabilities tailored to SME budgets, this solution employs subscription licensing and partner-managed cloud hosting to reduce upfront expenses and ongoing costs.', 'items' => array() ),
						array( 'title' => 'More Flexibility & Add-Ons', 'text' => 'Industry-specific add-ons and integrations enable businesses to customize their experience. Whether you operate in retail, manufacturing, or distribution, you can adapt workflows to fit your unique processes without sacrificing performance.', 'items' => array() ),
						array( 'title' => 'Data-Driven Decision Making', 'text' => 'Dynamic dashboards and key performance indicators present real-time insights that empower leaders to act swiftly. With accurate, up-to-date reporting, companies stay agile and competitive.', 'items' => array() ),
						array( 'title' => 'Regulatory Compliance', 'text' => 'The system ensures your operations meet Philippine tax standards, including BIR CAS requirements. Automated tax computations and continuous legal updates help maintain error-free, audit-ready records.', 'items' => array() ),
						array( 'title' => 'Deployment Options', 'text' => 'Choose from on-premise, cloud, or hybrid setups to align with your IT strategy and budget. Each option offers straightforward implementation and scalability for future growth.', 'items' => array() ),
					),
				),
				array(
					'type'    => 'generic',
					'title'   => 'SAP Business One ERP Features',
					'intro'   => array(
						'SAP Business One is designed to integrate and streamline all core business functions on a single platform, providing real-time access to critical data and improving operational efficiency. Its modular design covers a wide range of business needs, making it suitable for diverse industries and scalable for growing enterprises.',
					),
					'items'   => array(
						array( 'title' => 'Management and Administration', 'text' => 'Manage master data, approvals, and user access in one place to ensure control and process efficiency.', 'items' => array() ),
						array( 'title' => 'Inventory and Logistics', 'text' => 'Track inventory in real time with tools like barcode scanning and batch management to optimize stock levels.', 'items' => array() ),
						array( 'title' => 'Purchasing and Procurement', 'text' => 'Automate purchase orders and monitor supplier performance for smarter procurement and planning.', 'items' => array() ),
						array( 'title' => 'Sales and Customer Management', 'text' => 'Handle leads, sales, pricing, and service cases in one module to boost customer satisfaction.', 'items' => array() ),
						array( 'title' => 'Accounting and Financials', 'text' => 'Streamline core financial tasks—GL, payables, receivables, reports, and tax compliance.', 'items' => array() ),
						array( 'title' => 'Business Intelligence and Reporting', 'text' => 'Get real-time insights with customizable dashboards and drag-and-drop reporting tools.', 'items' => array() ),
						array( 'title' => 'Production and Manufacturing Management', 'text' => 'Plan production, manage BOMs, and oversee shop floor activities with full lifecycle visibility.', 'items' => array() ),
						array( 'title' => 'Project and Resource Management', 'text' => 'Track tasks, budgets, and resources to ensure projects stay on time and within scope.', 'items' => array() ),
						array( 'title' => 'Mobility and Cloud Deployment', 'text' => 'Access the system securely via mobile or web with flexible cloud and on-premise options.', 'items' => array() ),
					),
				),
				array(
					'type'    => 'generic',
					'title'   => 'Why is SAP Business One Suitable for Small Businesses?',
					'intro'   => array(
						'In today\'s competitive business landscape, small businesses require resource planning software that enables streamlined operations, informed decision-making, and sustainable growth. That\'s where SAP Business One comes in.',
						'Tailored specifically for small businesses and mid-sized enterprises in the Philippines, SAP Business One empowers you to optimize your operations, make data-driven decisions, and unlock new levels of success. Say goodbye to inefficiency and embrace a future of growth and prosperity with this digital solution.',
					),
					'items'   => array(
						array( 'title' => 'User-Friendly and Easy to Implement', 'text' => 'Experience the benefits of SAP Business One, where you\'ll enjoy an intuitive and user-friendly interface that can be easily customized to align with your business operations. You can also take advantage of cost-effective and efficient implementation packages utilizing SAP\'s Five-Phase Implementation Methodology. This approach ensures a streamlined and timely implementation, saving you valuable time and resources.', 'items' => array() ),
						array( 'title' => 'Scalable as the Business Grows', 'text' => 'SAP Business One offers extensive customization capabilities, making it the ideal solution for businesses of all sizes and industries. From custom workflows and fields to personalized dashboards and reports, it empowers you to adapt the system to match your business requirements. This level of customization ensures that the solution seamlessly aligns with your operations, enhancing efficiency and productivity.', 'items' => array() ),
						array( 'title' => 'Integrates with Other Software Systems', 'text' => 'SAP Business One is designed to seamlessly integrate with other software systems, allowing small businesses to consolidate their information and streamline operations. The system offers integration capabilities with applications such as Microsoft Office, customer relationship management systems, e-commerce platforms, and more.', 'items' => array() ),
						array( 'title' => 'Customizable for Any Business', 'text' => 'SAP Business One is your ally in business growth, constantly evolving to support your expanding operations and optimizing processes. With its high levels of customization and flexibility, this digital solution is tailored to meet your unique business needs.', 'items' => array() ),
					),
				),
				array(
					'type'    => 'generic',
					'title'   => 'Businesses that Utilize SAP Business One in the Philippines',
					'intro'   => array(
						'Experience the widespread adoption of SAP Business One across diverse industries in the Philippines. From manufacturing to retail, and from services to distribution, numerous companies have embraced this business planning software as their go-to solution for streamlining their processes, enhancing productivity, and fostering sustainable growth.',
					),
					'items'   => array(
						array( 'title' => 'Manufacturing Companies', 'text' => 'Optimize production, manage inventory, and enhance supplier collaboration for efficient operations and growth.', 'items' => array() ),
						array( 'title' => 'Retail Companies', 'text' => 'Oversee sales, track inventory, and streamline supply chains to boost customer satisfaction and profitability.', 'items' => array() ),
						array( 'title' => 'Professional Services', 'text' => 'Simplify client management, billing, and projects to reduce admin work and improve service quality.', 'items' => array() ),
						array( 'title' => 'IT Services', 'text' => 'Enhance financial management, project tracking, and CRM to boost workflow and business performance.', 'items' => array() ),
						array( 'title' => 'Food and Beverage Industry', 'text' => 'Monitor inventory, ensure safety compliance, and streamline logistics for quality and timely delivery.', 'items' => array() ),
						array( 'title' => 'Pharmaceutical and Healthcare', 'text' => 'Manage batch tracking, quality control, and compliance for safe, efficient supply chains.', 'items' => array() ),
						array( 'title' => 'Engineering, Procurement, and Construction (EPC)', 'text' => 'Automate workflows and improve project visibility for better coordination and outcomes.', 'items' => array() ),
						array( 'title' => 'Distribution and Logistics', 'text' => 'Manage inventory, orders, and logistics to ensure timely delivery and accurate stock control.', 'items' => array() ),
					),
				),
				array(
					'type'    => 'generic',
					'title'   => 'Why Choose DynamIQ as Your Provider of SAP Business One in the Philippines?',
					'intro'   => array(
						'When selecting a provider for SAP Business One in the Philippines, it\'s crucial to consider experience, support, and industry-specific solutions. That\'s where DynamIQ shines.',
						'As an SAP Business One Premier Partner, we not only bring expertise to the table but also work closely with your company to customize the system according to your specific business requirements. Rely on DynamIQ to be your trusted partner in uncovering the full potential of SAP Business One for your business.',
					),
					'items'   => array(
						array( 'title' => 'Support and Training', 'text' => 'DynamIQ offers clients <a href="https://dynamiqes.com/our-services/">technical support and user training</a> throughout the implementation of SAP Business One. Our commitment extends beyond the initial setup, as we provide guidance and assistance during software updates. Our dedicated team is available to troubleshoot any issues that may arise, ensuring smooth and efficient utilization of the digital solution.', 'items' => array() ),
						array( 'title' => 'Industry-Specific Solutions', 'text' => 'We also specialize in helping businesses across various industries, including retail, manufacturing, and distribution, select the ideal solution. By partnering with DynamIQ, companies can maximize efficiency, improve profitability, and harness the full potential of SAP Business One in the Philippines within their specific industry.', 'items' => array() ),
						array( 'title' => 'Integration with Other Systems and Applications', 'text' => 'We understand that companies may already work with third-party software. That’s why here at DynamIQ, we find ways to help you connect those applications to SAP Business One. Our expert team can help you seamlessly integrate this into your system.', 'items' => array() ),
						array( 'title' => 'Localization', 'text' => 'We play a crucial role in assisting businesses by helping them navigate regulations required by the Philippines government. This can include their annual Audited Financial Statement, Annual Information Returns, BIR Form 2316, and Annual Income Tax Returns.', 'items' => array() ),
					),
				),
				array(
					'type'    => 'cta',
					'title'   => 'Upgrade Your Business with SAP Business One in the Philippines with the Support of DynamIQ!',
					'intro'   => array(
						'Ready to unlock the full potential of your business and elevate it to new heights? Contact DynamIQ today and discover how SAP Business One in the Philippines drives operational excellence.',
						'With DynamIQ\'s team of experts, you\'ll receive tailored solutions that address your specific needs and requirements. From initial consultation to seamless implementation and after-sales support, DynamIQ is dedicated to ensuring your success with SAP Business One.',
						'Don\'t hesitate any longer—take the first step toward your business\'s success. <a href="https://dynamiqes.com/contact-us/">Contact DynamIQ</a> now to inquire and experience the transformative power of SAP Business One in the Philippines. Embrace this opportunity and gain a competitive edge in your industry with DynamIQ as your trusted partner.',
					),
				),
				array(
					'type'    => 'faq',
				),
			),
		),
		'portal' => array(
			'title'           => 'Elevate Your SAP Business One Experience with the DynamIQ Portal',
			'description'     => 'The DynamIQ Portal is a secure, web-based extension designed to enhance how teams interact with SAP Business One. Built or authorized users across your organization, it provides real-time access to critical business data—anytime, anywhere—while respecting role-based permissions.',
			'seo_title'       => 'SAP B1 Portal Module | Web-Based ERP Access Anytime, Anywhere',
			'seo_description' => 'Enhance SAP B1 with the DynamIQ Portal, a secure web-based extension for real-time access to sales, purchasing, inventory, and business data.',
			'overview_title'  => 'Product Overview',
			'overview'        => array(
				'Unlock the full potential of your SAP Business One system with our powerful add-on, designed to seamlessly enhance your ERP experience through the web. Our secure, user-friendly portal allows you to access and manage critical business data anytime, anywhere.',
				'Tailored to provide a lighter and faster experience, this solution empowers you to extend selected data and functionalities of SAP Business for better and more personalized user experience and integration to other 3rd party solutions. This ensures that you can streamline processes and respond to business needs effectively, all while enjoying the flexibility to work on your terms.',
				'Elevate your SAP Business One experience and take control of your data today!',
			),
			'closing'         => '',
			'faqs'            => array(
				array( 'Who can use the DynamIQ Portal?', '<p>The portal is designed for authorized users within your organization, such as business owners, managers, and team members who need real-time access to business data. Permissions can be customized based on user roles.</p>' ),
				array( 'What kind of data can I access through the DynamIQ Portal?', '<p>You can access all business data in your SAP Business One system, including sales, purchasing, inventory levels, approvals, and more. What data you can see through the DynamIQ portal will be based on your account’s access rights.</p>' ),
				array( 'How secure is the DynamIQ Portal?', '<p>Security is a top priority. The portal uses end-to-end encryption and IQLicense to ensure secure and client-only access to protect sensitive business data.</p>' ),
				array( 'Can I use the DynamIQ Portal on mobile devices?', '<p>Yes. The portal is fully responsive and optimized for desktops, tablets, and smartphones, allowing you to manage your business operations on the go.</p>' ),
				array( 'Is training required to use the DynamIQ Portal?', '<p>The portal is designed to be intuitive and easy to navigate. However, the DynamIQ team is ready to assist and provide training and/or user guides to help your organization and/or new users get started quickly and confidently.</p>' ),
				array( 'How often is the data updated in the DynamIQ Portal?', '<p>The portal provides real-time or near real-time data, depending on your system configuration. This ensures you always have access to the most current information available.</p>' ),
			),
			'faq_heading'     => 'p',
			'sections'        => array(
				array(
					'type'    => 'overview',
				),
				array(
					'type'    => 'generic',
					'title'   => 'IQ Portal Features',
					'intro'   => array(
						'The DynamIQ Portal, considerably an ideal front-end interface, allows seamless integration to SAP Business One.',
					),
					'items'   => array(
						array( 'title' => 'Sales', 'text' => '', 'items' => array(
							'Sales Quotation',
							'Sales Order',
							'Sales Delivery',
							'Sales Return',
						) ),
						array( 'title' => 'Purchasing', 'text' => '', 'items' => array(
							'Purchase Request',
							'Purchase Order',
							'Good Receipt PO',
							'Goods Return',
						) ),
						array( 'title' => 'Inventory', 'text' => '', 'items' => array(
							'Goods Receipt',
							'Goods Issue',
							'Inventory Transfer Request',
							'Inventory Transfer',
							'Inventory Counting',
						) ),
					),
				),
				array(
					'type'    => 'faq',
				),
			),
		),
		'tax' => array(
			'title'           => 'Streamline BIR Compliance with the DynamIQ Tax Module for SAP Business One',
			'description'     => 'The DynamIQ Tax Module is a BIR-compliant taxation solution built by DynamIQ to enhance SAP Business One’s financial capabilities. Designed to support electronic tax filing requirements, it enables businesses to generate BIR forms, reports, and DAT file attachments in just one click.',
			'seo_title'       => 'SAP B1 Tax Module | BIR-Compliant | Paperless Tax Filing & Compliance',
			'seo_description' => 'A BIR-compliant system to help you break free from your tax filing dilemma. Generate your transactional BIR forms and reports including DAT file attachments in just one click! Inquire today!',
			'overview_title'  => 'Product Overview',
			'overview'        => array(
				'While BIR’s intent to digitized is clear, many taxpayers oftentimes find themselves in disarray with the process because of its complicated forms and risky manual data entry. This is why businesses need a reliable accounting system in the Philippines.',
				'We have created an application suitably compatible with SAP Business One to reduce the tax filing bottlenecks and enhance paperless tax filing experience.',
				'DYNAMIQ BIR TAX MODULE, our proprietary taxation program, is designed to make tax filing and compliance easy and accessible at a click of a button. It is in compliance to the computerized accounting system (CAS) and in pursuance to BIR-issued Revenue Regulation (RR) 9-2009 and Revenue Memorandum 29-2002.',
			),
			'closing'         => '',
			'faqs'            => array(
				array( 'How does the DynamIQ BIR Tax Module improve tax compliance compared to manual methods?', '<p>Manual tax filing is prone to human error, missed deadlines, and data inconsistencies. The DynamIQ BIR Tax Module automates form generation and reporting directly from SAP Business One data, significantly reducing filing time and increasing accuracy—ensuring compliance with the BIR’s digital mandates.</p>' ),
				array( 'How does the BIR Tax Module integrate with SAP Business One?', '<p>The module pulls financial and transactional data directly from SAP Business One, enabling real-time generation of tax forms, reports, and books of accounts without manual data entry.</p>' ),
				array( 'Can this module help us eliminate duplicate data entry between our accounting system and BIR applications?', '<p>Yes. Since the module integrates natively with SAP Business One, it removes the need to manually re-enter data into standalone applications like eBIRForms. This improves workflow efficiency and ensures your tax forms always reflect your actual books.</p>' ),
				array( 'Is the module regularly updated to follow changes in BIR regulations or form revisions?', '<p>Absolutely. Our team actively monitors BIR announcements and updates the module as needed to ensure continuous compliance. You’ll receive notifications for any critical updates and patches.</p>' ),
				array( 'Can the BIR Tax Module be customized for my business needs and industry-specific requirements?', '<p>Yes. Whether you\'re a growing SME or a large enterprise, the module can be configured to match your operations, volume of transactions, and industry-specific tax filing needs.</p>' ),
				array( 'Is user training or support available?', '<p>Yes. You’ll receive full post-implementation support, including troubleshooting assistance, module updates, and user guidance. We also offer refresher training sessions upon request.</p>' ),
				array( 'How long does implementing the BIR Tax Module usually take?', '<p>Implementation timelines vary depending on your current SAP Business One setup and specific business requirements. However, most installations with standard configurations can be completed in a few days—including testing and user training.</p>' ),
				array( 'Can we export the data and reports generated by the module for internal audits or external use?', '<p>Yes. All generated forms, journals, and reports can be exported in commonly used formats (e.g., PDF, Excel, DAT), making it easy to support audits, financial reviews, and document submissions.</p>' ),
				array( 'Do we need to be CAS-registered to use this module?', '<p>CAS registration is not required to start using the module. However, it is essential if you plan to apply for BIR CAS accreditation, since one of the key requirements is the electronic generation of BIR reports. This module is designed to support that need and help ensure your system is compliant during the application process.</p>' ),
				array( 'How do we know if this module is the right fit for our company?', '<p>If your business handles frequent tax filings, high transaction volumes, or wants to eliminate manual entries while ensuring compliance, this module is designed for you. It\'s flexible and can be customized to cater to any industry. We also offer demos to help you evaluate its fit before implementation.</p>' ),
			),
			'faq_heading'     => 'p',
			'sections'        => array(
				array(
					'type'    => 'overview',
				),
				array(
					'type'    => 'generic',
					'title'   => 'DynamIQ Tax Features',
					'intro'   => array(
						'Made available as a tax add-on module for SAP Business One, it is developed specifically as an alternative solution for eBIRForms and Alphalist Data Entry applications. This module will allow taxpayers to automate the generation of transactional BIR forms and reports including DAT file attachments.',
					),
					'items'   => array(
						array( 'title' => 'BIR Forms', 'text' => '', 'items' => array(
							'0619-E',
							'1601-EQ',
							'1604-E',
							'2550M',
							'2550Q',
							'2307',
						) ),
						array( 'title' => 'Books of Accounts', 'text' => '', 'items' => array(
							'General Ledger',
							'General Journal',
							'Sales Journal',
							'Purchase Journal',
							'Cash Receipt Journal',
							'Cash Disbursement Journal',
							'Inventory Journal',
							'Debit/Credit Memo Journal',
						) ),
						array( 'title' => 'VAT Reports', 'text' => '', 'items' => array(
							'BIR Vat Relief',
							'Purchases',
							'Purchases Importation',
							'Sales',
							'Input VAT Report Output VAT Report',
						) ),
						array( 'title' => 'Withholding Tax Reports', 'text' => '', 'items' => array(
							'EWT Report',
							'CWT Report',
							'SAWT',
							'MAP',
						) ),
					),
				),
				array(
					'type'    => 'faq',
				),
			),
		),
		'barcode' => array(
			'title'           => 'Enhance Inventory Accuracy with DynamIQ’s Barcode Integration',
			'description'     => 'DynamIQ Barcode is a third-party inventory integration designed to extend SAP Business One with barcode-driven tracking and scanning capabilities. Built for businesses that require speed, accuracy, and traceability, it supports both batch-managed and serial-managed items across industries such as food and beverage, pharmaceuticals, and electronics.',
			'seo_title'       => 'SAP B1 Barcode Module - DynamIQ',
			'seo_description' => 'DynamIQ Barcoding is a third-party SAP Business One integration that streamlines scanning, tracking, and inventory control for faster, more accurate operations.',
			'overview_title'  => 'Product Overview',
			'overview'        => array(
				'IQ Barcode is a robust barcode inventory solution seamlessly integrated with SAP Business On. It enhances your logistics workflow enabling fast, accurate tracking items through barcode scanning-bringing efficiency, reliability, and real time visibility to your operations.',
			),
			'closing'         => '',
			'faqs'            => array(
				array( 'How does this module impact warehouse and inventory accuracy?', '<p>By scanning items at every stage of the logistics process—receiving, picking, packing, and dispatch—the system ensures real-time updates to your inventory in SAP B1. This greatly minimizes errors and improves inventory visibility and control.</p>' ),
				array( 'Is the module compatible with all barcode scanners?', '<p>The DynamIQ Barcoding Module supports a wide range of industry-standard barcode scanners. We recommend models that are SAP-certified or Android-based for optimal compatibility and performance. Specific device recommendations are available upon request.</p>' ),
				array( 'Can it support batch or serial number tracking?', '<p>Yes. The module supports both batch-managed and serial number-managed items, making it ideal for industries requiring traceability such as food &amp; beverage, pharmaceuticals, and electronics.</p>' ),
				array( 'Does the module work in real time?', '<p>Yes. Barcode scan data is processed and pushed in real time to SAP Business One, ensuring your inventory levels and warehouse status are always up to date.</p>' ),
				array( 'Can the module handle multiple warehouses or storage locations?', '<p>Absolutely. The DynamIQ Barcoding Module supports multi-warehouse and bin location management, allowing you to track stock movements across different locations with precision.</p>' ),
				array( 'Does the module require internet connectivity to function?', '<p>For real-time syncing with SAP B1, a stable connection is required. However, some offline functionality can be configured depending on the scanner used, with data synced once connectivity is restored.</p>' ),
				array( 'How long does it take to implement the DynamIQ Barcoding Module, and what does that process involve?', '<p>Implementation time varies depending on the size of your warehouse, the number of users, and the complexity of your inventory processes. It includes a system assessment, configuration aligned with your SAP Business One setup, hardware compatibility checks, barcode mapping, user training, and live testing.</p>' ),
				array( 'What kind of post-implementation support is available?', '<p>We offer comprehensive support including software updates, technical troubleshooting, and user assistance. Custom enhancements can also be discussed based on evolving operational needs.</p>' ),
			),
			'faq_heading'     => 'p',
			'sections'        => array(
				array(
					'type'    => 'overview',
				),
				array(
					'type'    => 'faq',
				),
			),
		),
		'link' => array(
			'title'           => 'Integrate Your Systems Seamlessly with IQ Link for SAP Business One',
			'description'     => 'Connect SAP B1 to POS, e-commerce platforms, WMS, CRM tools, or custom legacy software. IQ Link ensures real-time or scheduled data syncing while monitoring for inconsistencies, giving your operations a unified, error-resistant workflow.',
			'seo_title'       => 'IQ Link Integration Module for SAP Business One | Connect POS, HRIS, & More',
			'seo_description' => 'Use DyanmIQ\'s IQ Link to bring together the different types of software you may be using. Click here to learn more about this SAP Business One Integration!',
			'faqs'            => array(
				array( 'What types of systems can IQ Link integrate with SAP Business One?', '<p>IQ Link can connect SAP B1 with a wide range of systems, including:</p><ul><li>Point-of-Sale (POS) software</li><li>E-commerce platforms</li><li>Warehouse Management Systems (WMS)</li><li>CRM tools</li><li>Custom legacy systems</li></ul><p>If your software supports data exchange (via APIs, file-based imports, or database-level sync), it can likely be integrated through IQ Link.</p>' ),
				array( 'How does IQ Link handle data inconsistencies between systems?', '<p>IQ Link features a built-in status report that flags mismatched or missing data in real time. This allows users to proactively correct issues before they affect operations or reporting, helping maintain data integrity across connected systems.</p>' ),
				array( 'Is the integration done in real time or in batches?', '<p>IQ Link supports both real-time and scheduled (batch) data synchronization, depending on the needs and capabilities of the systems being integrated. Real-time syncing is ideal for operations like inventory or sales, while batch sync may suit reporting or legacy system updates.</p>' ),
				array( 'Can IQ Link be customized to fit our unique system architecture?', '<p>Yes. IQ Link is highly adaptable and can be configured to match your specific business logic, field mappings, and data transformation requirements. Our team will assess your existing infrastructure and develop a custom integration plan that works for your operations.</p>' ),
				array( 'How do we monitor or troubleshoot integration issues?', '<p>IQ Link includes a user-friendly dashboard where you can view integration logs, check status reports, and identify sync errors or delays. This transparency empowers your IT or operations team to quickly diagnose and resolve any issues.</p>' ),
				array( 'How long does integration with IQ Link usually take?', '<p>The timeline depends on the number of systems being integrated and the complexity of their data structures. Simple one-way connections can be set up in a matter of days, while more complex bi-directional syncs may take several weeks.</p>' ),
				array( 'How do we know if IQ Link is the right solution for our integration needs?', '<p>If you use multiple disconnected systems and want to centralize your data in SAP B1—or reduce the time spent on manual reconciliation—IQ Link is a smart solution. A consultation and system audit can help determine the best-fit integration strategy for your business.</p>' ),
				array( 'Will integrating systems via IQ Link affect our current SAP setup?', '<p>No. IQ Link is designed to integrate without disrupting your existing SAP Business One configuration. It works alongside your current setup and enhances it by bridging data between platforms.</p>' ),
			),
			'faq_heading'     => 'p',
			'sections'        => array(
				array(
					'type'    => 'faq',
				),
			),
		),
		'rem' => array(
			'title'           => 'Smarter Real Estate Management with IQ REM for SAP Business One',
			'description'     => 'Optimize your real estate sales and financial processes with IQ REM, the powerful SAP Business One add-on built for developers and real estate professionals.',
			'seo_title'       => 'SAP B1 Real Estate Management Module | Streamline Property Sales & Financials',
			'seo_description' => 'Optimize your leasing, sales, and property management with IQ REM, a powerful real estate management system designed for SAP B1.',
			'overview_title'  => 'Product Overview',
			'overview'        => array(
				'IQ REM is a powerful and versatile add-on for SAP Business One (SAP B1), specifically designed to streamline and enhance the management of real estate sales and associated financial transactions. Tailored for developers, real estate professionals, and businesses, IQ REM integrates seamlessly with SAP B1 to provide an all-in-one solution for handling the complexities of real estate operations.',
				'DynamIQ Real Estate Management empowers real estate businesses to focus on growth and customer satisfaction by reducing administrative burdens and increasing operational efficiency.',
			),
			'closing'         => '',
			'faqs'            => array(
				array( 'What makes IQ REM different from other real estate management software?', '<p>Unlike standalone real estate software, IQ REM is fully integrated with SAP Business One. This means your sales, billing, contracts, and financials all work from a single source of truth, reducing manual processes and enabling end-to-end visibility into your real estate business.</p>' ),
				array( 'Can IQ REM handle both residential and commercial property sales?', '<p>Yes. IQ REM is built to support diverse property types, including residential units, commercial spaces, buildings, and subdivisions. You can customize unit classifications, pricing schemes, and contract types based on your project needs.</p>' ),
				array( 'Can we generate reports on unit availability and sales performance?', '<p>Yes. IQ REM offers real-time dashboards and reporting tools that give you visibility into available inventory, sold units, customer payment status, and project performance, helping you make faster, data-driven decisions.</p>' ),
				array( 'Is IQ REM scalable as our real estate portfolio grows?', '<p>Definitely. DynamIQ’s IQ REM is built to scale with your operations—whether you’re handling one development or managing multiple projects and locations. You can add more properties, users, and workflows as needed without disrupting your existing setup.</p>' ),
				array( 'How long does it take to implement IQ REM for an existing SAP B1 user?', '<p>Typical implementation can take a few weeks, depending on the complexity of your real estate operations and the volume of historical data to be migrated. We conduct discovery, configuration, training, and testing to ensure a smooth rollout.</p>' ),
				array( 'Is customer data secure in the system?', '<p>Yes. The IQ REM module follows SAP Business One’s security protocols, including user access controls and audit trails. Sensitive customer, financial, and property data is protected at every stage of the workflow.</p>' ),
			),
			'faq_heading'     => 'p',
			'sections'        => array(
				array(
					'type'    => 'overview',
				),
				array(
					'type'    => 'faq',
					'heading' => false,
				),
			),
		),
		'ai' => array(
			'title'           => 'Unlock Intelligent Automation with IQ Ai by DynamIQ',
			'description'     => 'IQ Ai is a next-generation Ai-powered engine built by DynamIQ Enterprise Solution Inc. to extend the capabilities of SAP Business One. It uses machine learning, natural language processing, and intelligent automation to help you.',
			'seo_title'       => 'AI Module for SAP Business One ERP - DynamIQes',
			'seo_description' => 'Upgrade your SAP Business One ERP productivity with an AI Module. Automate insights, streamline operations, and drive smarter decisions with integrated AI.',
			'overview_title'  => 'Smarter Insights, Smoother Operations: An Overview of IQ Ai',
			'overview'        => array(
				'IQ Ai is an intelligent solution designed to work seamlessly with SAP Business One. It harnesses the power of artificial intelligence to turn your business data into real-time insights, smart recommendations, and automated actions—so you can work smarter, not harder.',
			),
			'closing'         => '',
			'faqs'            => array(),
			'sections'        => array(
				array(
					'type'    => 'overview',
				),
				array(
					'type'    => 'generic',
					'title'   => 'Key Capabilities of IQ Ai',
					'list'    => array(
						'Predictive Insights',
						'Automated Analysis',
						'Conversational Intelligence',
						'Process Automation',
						'Smart Alerts & Recommendations',
					),
				),
			),
		),
		'desk' => array(
			'title'           => 'IQDesk: Smarter IT Service, All in One Place.',
			'description'     => 'IQDesk is DynamIQ’s all-in-one IT Service Management (ITSM) and helpdesk solution built to make IT support simpler, faster, and easier to manage.',
			'seo_title'       => 'IT Service Management Module for SAP B1 - DynamIQes',
			'seo_description' => 'Simplify IT support with IQ Desk for SAP Business One. Manage tickets, track assets with PAR, automate workflows, and improve response efficiency.',
			'overview_title'  => 'Product Overview',
			'overview'        => array(
				'IQDesk is DynamIQ’s all-in-one platform designed to simplify how businesses handle IT support, manage assets, and keep operations running smoothly. It goes beyond basic support by helping you stay in full control of your IT resources and other assets. With built-in Property Acknowledgement Receipt (PAR) tracking, you’ll always know who’s responsible for each asset, complete with proper documentation and e-signatures for accountability.',
				'DynamIQ Desk also uses smart automation to support your team by suggesting replies, summarizing tickets, and automatically routing requests, while providing a confidence level so agents can quickly assess the reliability of each response.',
			),
			'closing'         => '',
			'faqs'            => array(),
			'sections'        => array(
				array(
					'type'    => 'overview',
				),
				array(
					'type'    => 'generic',
					'title'   => 'Smarter Tools for Modern Workflows',
					'intro'   => array(
						'Explore IQ Desk’s latest features designed to improve efficiency, simplify processes, and support effective day-to-day business operations.',
					),
					'items'   => array(
						array( 'title' => 'Smart Help Desk', 'text' => '', 'items' => array(
							'AI-assisted ticketing',
							'Auto-drafted replies',
							'Live agent escalation',
							'Multi-channel support via portal, email, and chat',
							'24/7 first-line assistance',
						) ),
						array( 'title' => 'Ticket Management', 'text' => '', 'items' => array(
							'Open, working, solved, and closed statuses',
							'Resolution tracking',
							'Timeline logs',
							'Confidence-based AI response suggestions',
						) ),
						array( 'title' => 'Asset Management', 'text' => '', 'items' => array(
							'Hardware and software asset tracking',
							'Asset barcode support',
							'Serial number and technical profile recording',
							'Warranty, vendor, and purchase cost tracking',
							'Property acknowledgement receipt with e-signature',
						) ),
						array( 'title' => 'Asset Audit & Reports', 'text' => '', 'items' => array(
							'Barcode-based asset checking',
							'Audit mode for asset validation',
							'Check if the asset still exists/is still assigned',
							'Upload and update assets using reports',
							'Generate asset-based reports, including Belarc-style asset/system reports',
						) ),
						array( 'title' => 'User & Access Control', 'text' => '', 'items' => array(
							'User directory',
							'Department and company assignment',
							'Check if the asset still exists/is still assigned',
							'Role-based permissions',
							'Module authorization',
						) ),
						array( 'title' => 'Automation & Integrations', 'text' => '', 'items' => array(
							'AI knowledge-based assistance',
							'Notification and email settings',
							'Import/export and bulk upload',
							'Integration with Telegram, WhatsApp, Slack, and Teams',
						) ),
					),
				),
			),
		),
		'ecom' => array(
			'title'           => 'Advance Your B2B and B2C E-commerce with IQEcom for SAP Business One',
			'description'     => 'IQEcom is DynamIQ’s enterprise-grade B2B and B2C e-commerce platform designed for businesses that go beyond simple online selling. It is built for real-world operations where pricing is negotiated, purchases require approval, and inventory needs to be tracked across multiple locations.',
			'seo_title'       => 'E-Commerce Platform Module for SAP B1 - DynamIQes',
			'seo_description' => 'Run e-commerce seamlessly with IQ Ecom for SAP Business One. Sync orders, inventory, and pricing while eliminating double encoding and manual errors.',
			'overview_title'  => 'Product Overview',
			'overview'        => array(
				'With IQEcom, you are not just putting products online. You are creating a structured and controlled buying experience that reflects how your business actually operates. Designed to work seamlessly with SAP Business One, IQEcom connects your front-end sales with your back-end operations. This means no double encoding, no disconnected systems, and a single, streamlined process from order to fulfillment.',
				'Multiple pricelists. One platform. Assign unique pricing per customer type, retail walk-ins, resellers, or tiered wholesalers. Each buyer logs in and sees only the price agreed with them. No manual overrides, no confusion.',
			),
			'closing'         => '',
			'faqs'            => array(),
			'sections'        => array(
				array(
					'type'    => 'overview',
				),
				array(
					'type'    => 'generic',
					'title'   => 'Built for Smarter E-Commerce Growth',
					'intro'   => array(
						'Discover powerful features that enhance your online store’s performance—from product management to customer experience—helping you scale with confidence and control.',
					),
					'items'   => array(
						array( 'title' => 'Real Time Financial Transparency', 'text' => 'Gain immediate access to the current balance and statement of accounts.', 'items' => array() ),
						array( 'title' => 'Real-Time Order Tracking', 'text' => 'Receive live updates on order status, including tracking numbers and courier information.', 'items' => array() ),
						array( 'title' => 'Specialized Discount Management', 'text' => 'Allows complex pricing configurations, including percentage or fixed amounts for different types of clients.', 'items' => array() ),
						array( 'title' => 'Multi-Warehouse Support', 'text' => 'Manage stock and fulfillment across multiple warehouse locations to ensure accurate inventory management.', 'items' => array() ),
						array( 'title' => 'Intelligent Product Visibility', 'text' => 'A permission system that shows or hides products based on who is logged in - a system where certain products are only visible to the right people', 'items' => array() ),
						array( 'title' => 'Seamless SAP Integration', 'text' => 'Automatically syncs warehouses and items while generating sales orders directly into SAP Business One to eliminate manual data entry.', 'items' => array() ),
					),
				),
			),
		),
	);
}
